---
apiVersion: v1
kind: Service
metadata:
  name: rsshd-ssh
  namespace: __NAMESPACE__
spec:
  selector:
    ssh-app: rsshd
  ports:
    - protocol: TCP
      port: 2222
      name: sshd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsshd
  namespace: __NAMESPACE__
spec:
  selector:
    matchLabels:
      ssh-app: rsshd
  template:
    metadata:
      labels:
        ssh-app: rsshd
__LABELS__
    spec:
      containers:
      - name: sshd
        image: docker.io/mweindel/rsshd:0.2
        imagePullPolicy: Always
        command: ['/usr/local/bin/sshd.sh']
        env:
        - name: AUTHORIZED_KEYS
          value: __AUTHORIZED_KEYS__
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        ports:
        - containerPort: 2222
          name: sshd
