---
apiVersion: v1
kind: Service
metadata:
  name: rsshd-ssh
  namespace: default
spec:
  selector:
    app: rsshd
  ports:
    - protocol: TCP
      port: 22
      name: sshd
---
apiVersion: v1
kind: Service
metadata:
  name: rsshd-webhook1
  namespace: default
spec:
  selector:
    app: rsshd
  ports:
    - protocol: TCP
      port: 443
      targetPort: 10000
---
apiVersion: v1
kind: Pod
metadata:
  name: rsshd
  labels:
    app: rsshd
spec:
  containers:
  - name: sshd
    image: docker.io/mweindel/rsshd:latest
    imagePullPolicy: Always
    command: ['/usr/local/bin/sshd.sh']
    env:
    - name: AUTHORIZED_KEYS
      value: ssh-rsa XXXX
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 200Mi
    ports:
    - containerPort: 22
      name: sshd
    - containerPort: 10000
      name: p0
    - containerPort: 10001
      name: p1
    - containerPort: 10002
      name: p2
